# Generated by Django 3.0.8 on 2021-07-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0004_auto_20210724_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=250)),
                ('is_vegan', models.BooleanField(default=False)),
                ('publish_date', models.CharField(default='', max_length=250)),
                ('update_date', models.CharField(default='', max_length=250)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.Menu')),
            ],
            options={
                'verbose_name': ['option'],
                'verbose_name_plural': 'options',
                'ordering': ['-publish_date'],
            },
        ),
    ]
