# Generated by Django 3.0.8 on 2021-07-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={},
        ),
        migrations.AlterField(
            model_name='option',
            name='publish_date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='option',
            name='update_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
