# Generated by Django 3.0.8 on 2021-07-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('published_date', models.CharField(default='', max_length=10, unique=True)),
                ('update_date', models.TextField()),
            ],
        ),
    ]
