# Generated by Django 3.0.8 on 2021-07-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='update_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
