# Generated by Django 3.0.8 on 2021-07-26 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('option', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_uuid', models.CharField(default='', max_length=50)),
                ('option_uuid', models.CharField(default='', max_length=50)),
                ('customization', models.CharField(default='', max_length=250)),
                ('username', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('status_order', models.BooleanField(default=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='option.Option')),
            ],
        ),
    ]
