# Generated by Django 3.0.8 on 2021-07-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210726_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
